//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: packets.proto

package ca.damocles.proto;

@kotlin.jvm.JvmSynthetic
inline fun serverPacketkt(block: ca.damocles.proto.ServerPacketktKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacketkt =
  ca.damocles.proto.ServerPacketktKt.Dsl._create(ca.damocles.proto.Packets.ServerPacketkt.newBuilder()).apply { block() }._build()
object ServerPacketktKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.damocles.proto.Packets.ServerPacketkt.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.damocles.proto.Packets.ServerPacketkt.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.damocles.proto.Packets.ServerPacketkt = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.damocles.proto.Packets.ServerPacketkt.copy(block: ca.damocles.proto.ServerPacketktKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacketkt =
  ca.damocles.proto.ServerPacketktKt.Dsl._create(this.toBuilder()).apply { block() }._build()
