//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: packets.proto

package ca.damocles.proto;

@kotlin.jvm.JvmSynthetic
inline fun serverPacket(block: ca.damocles.proto.ServerPacketKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacket =
  ca.damocles.proto.ServerPacketKt.Dsl._create(ca.damocles.proto.Packets.ServerPacket.newBuilder()).apply { block() }._build()
object ServerPacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.damocles.proto.Packets.ServerPacket.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.damocles.proto.Packets.ServerPacket.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.damocles.proto.Packets.ServerPacket = _builder.build()
  }
  @kotlin.jvm.JvmSynthetic
  inline fun responsePacket(block: ca.damocles.proto.ServerPacketKt.ResponsePacketKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacket.ResponsePacket =
    ca.damocles.proto.ServerPacketKt.ResponsePacketKt.Dsl._create(ca.damocles.proto.Packets.ServerPacket.ResponsePacket.newBuilder()).apply { block() }._build()
  object ResponsePacketKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    class Dsl private constructor(
      private val _builder: ca.damocles.proto.Packets.ServerPacket.ResponsePacket.Builder
    ) {
      companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: ca.damocles.proto.Packets.ServerPacket.ResponsePacket.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): ca.damocles.proto.Packets.ServerPacket.ResponsePacket = _builder.build()

      /**
       * <code>int32 code = 1;</code>
       */
      var code: kotlin.Int
        @JvmName("getCode")
        get() = _builder.getCode()
        @JvmName("setCode")
        set(value) {
          _builder.setCode(value)
        }
      /**
       * <code>int32 code = 1;</code>
       */
      fun clearCode() {
        _builder.clearCode()
      }

      /**
       * <code>string message = 2;</code>
       */
      var message: kotlin.String
        @JvmName("getMessage")
        get() = _builder.getMessage()
        @JvmName("setMessage")
        set(value) {
          _builder.setMessage(value)
        }
      /**
       * <code>string message = 2;</code>
       */
      fun clearMessage() {
        _builder.clearMessage()
      }
    }
  }
  @kotlin.jvm.JvmSynthetic
  inline fun pingPacket(block: ca.damocles.proto.ServerPacketKt.PingPacketKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacket.PingPacket =
    ca.damocles.proto.ServerPacketKt.PingPacketKt.Dsl._create(ca.damocles.proto.Packets.ServerPacket.PingPacket.newBuilder()).apply { block() }._build()
  object PingPacketKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    class Dsl private constructor(
      private val _builder: ca.damocles.proto.Packets.ServerPacket.PingPacket.Builder
    ) {
      companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: ca.damocles.proto.Packets.ServerPacket.PingPacket.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): ca.damocles.proto.Packets.ServerPacket.PingPacket = _builder.build()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.damocles.proto.Packets.ServerPacket.copy(block: ca.damocles.proto.ServerPacketKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacket =
  ca.damocles.proto.ServerPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
inline fun ca.damocles.proto.Packets.ServerPacket.ResponsePacket.copy(block: ca.damocles.proto.ServerPacketKt.ResponsePacketKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacket.ResponsePacket =
  ca.damocles.proto.ServerPacketKt.ResponsePacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
inline fun ca.damocles.proto.Packets.ServerPacket.PingPacket.copy(block: ca.damocles.proto.ServerPacketKt.PingPacketKt.Dsl.() -> kotlin.Unit): ca.damocles.proto.Packets.ServerPacket.PingPacket =
  ca.damocles.proto.ServerPacketKt.PingPacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()
